### ISSUE TITLE
contains references to both AndroidX and old support library

### ISSUE THREAD

**Issue by jrcacd** [okdroid/checkable-chip-view#26]
checkablechipview-1.0.2.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/content/res/TypedArrayKt'
 Example of support library reference: 'android/support/v4/graphics/ColorUtils'

**Comment by hailemix** [comment]
I've got a similar error here...
`C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:9: warning: [deprecation] AsyncTask in android.os has been deprecated
import android.os.AsyncTask;
                 ^
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask in android.os has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
        ^
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
    ^
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:123: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
      protected Boolean doInBackground(Void... voids) {
                        ^
  where Params,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
                                         ^
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:128: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
      protected void onPostExecute(Boolean value) {
                     ^
  where Result is a type-variable:
    Result extends Object declared in class AsyncTask
C:\flutterbeta\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:131: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
    }.execute();
     ^
  where Params,Progress,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Progress extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
7 warnings
`

**Comment by markushi** [comment]
Closing this as the `2.0.0` release fully switched to AndroidX already.
