### ISSUE TITLE
checkablechipview contains references to both AndroidX and old support library

### ISSUE THREAD

**Issue by jrcacd** [okdroid/checkable-chip-view#28]
WARNING: [Processor] Library 'C:\Users\aaa\.gradle\caches\modules-2\files-2.1\com.github.okdroid\checkablechipview\1.0.2\c5804934c3754214b7881f1cf60216faebecc4af\checkablechipview-1.0.2.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated.

**Comment by markushi** [comment]
Duplicate of #26, please use version `2.0.0`

**Comment by jrcacd** [comment]
Ok, thanks
